name = "TransportMaps"
uuid = "6fd49bf0-03ac-4dd1-b9b3-42e511274d6e"
version = "1.0.0-DEV"
authors = ["Lukas Fritsch <fritsch@irz.uni-hannover.de>", "Jan Grashorn <grashorn@hsu-hh.de>"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
Distributions = "0.25.120"
FastGaussQuadrature = "1.0.2"
ForwardDiff = "1.0.1"
LinearAlgebra = "1.11.0"
Optim = "1.13.2, 2.0"
QuasiMonteCarlo = "0.3.3"
Random = "1.11.0"
Statistics = "1.11.1"
StatsFuns = "1.5.0"
julia = "1.11, 1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
